[package]
name = "shippingservice"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shippingservice"
path = "src/main.rs"

[features]
dockerproto = [] # compile in docker or not

[dependencies]
tonic = "0.8"
tonic-health = "0.7.1"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
prost = "0.11"
prost-types = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
opentelemetry = { version = "0.18", features = ["rt-tokio", "trace"] }
opentelemetry_api = { version = "0.18" }
opentelemetry-http = "0.7.0"
opentelemetry-otlp = "0.11.0"
log = "0.4.17"
simplelog = "0.12"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[build-dependencies]
tonic-build = "0.8"