version: '3.7'

services:
  postgres:
    image: cimg/postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=featureflagservice_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    ports:
      - 5432:5432
