# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      push:
        description: Should the images be pushed
        default: false
        required: false
        type: boolean
      version:
        description: The version used when tagging the image
        default: 'dev'
        required: false
        type: string
      dockerhub_repo:
        description: Docker Hub repository
        default: 'otel/demo'
        required: false
        type: string
      ghcr_repo:
        description: GHCR repository
        default: 'ghcr.io/open-telemetry/demo'
        required: false
        type: string

jobs:
  build_and_push_images:
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read
      packages: write

    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, otel-linux-arm64]
        file_tag:
          - file: ./src/accountingservice/Dockerfile
            tag_suffix: accountingservice
            context: ./
          - file: ./src/adservice/Dockerfile
            tag_suffix: adservice
            context: ./
          - file: ./src/cartservice/src/Dockerfile
            tag_suffix: cartservice
            context: ./
          - file: ./src/checkoutservice/Dockerfile
            tag_suffix: checkoutservice
            context: ./
          - file: ./src/currencyservice/Dockerfile
            tag_suffix: currencyservice
            context: ./
          - file: ./src/emailservice/Dockerfile
            tag_suffix: emailservice
            context: ./src/emailservice
          - file: ./src/frauddetectionservice/Dockerfile
            tag_suffix: frauddetectionservice
            context: ./
          - file: ./src/frontend/Dockerfile
            tag_suffix: frontend
            context: ./
          - file: ./src/frontendproxy/Dockerfile
            tag_suffix: frontendproxy
            context: ./
          - file: ./src/frontend/Dockerfile.cypress
            tag_suffix: frontend-tests
            context: ./
          - file: ./src/imageprovider/Dockerfile
            tag_suffix: imageprovider
            context: ./
          - file: ./src/kafka/Dockerfile
            tag_suffix: kafka
            context: ./
          - file: ./src/loadgenerator/Dockerfile
            tag_suffix: loadgenerator
            context: ./
          - file: ./src/paymentservice/Dockerfile
            tag_suffix: paymentservice
            context: ./
          - file: ./src/productcatalogservice/Dockerfile
            tag_suffix: productcatalogservice
            context: ./
          - file: ./src/quoteservice/Dockerfile
            tag_suffix: quoteservice
            context: ./
          - file: ./src/recommendationservice/Dockerfile
            tag_suffix: recommendationservice
            context: ./
          - file: ./src/shippingservice/Dockerfile
            tag_suffix: shippingservice
            context: ./
          - file: ./test/tracetesting/Dockerfile
            tag_suffix: traceBasedTests
            context: ./

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes and set push options
        id: check_changes
        run: |
          DOCKERFILE_DIR=$(dirname ${{ matrix.file_tag.file }})
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- $DOCKERFILE_DIR)
          FORCE_PUSH=${{ inputs.push }}
          if [ "$FORCE_PUSH" = true ]; then
            echo "Force push is enabled, proceeding with build."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          elif [ -z "$FILES_CHANGED" ]; then
            echo "No changes in ${{ matrix.file_tag.context }}, skipping build."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected in ${{ matrix.file_tag.context }}, proceeding with build."
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.push }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ inputs.push }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Matrix Build and push demo images
        if: steps.check_changes.outputs.skip == 'false'
        uses: docker/build-push-action@v6.0.0
        with:
          context: ${{ matrix.file_tag.context }}
          file: ${{ matrix.file_tag.file }}
          push: ${{ inputs.push }}
          tags: |
            ${{ inputs.dockerhub_repo }}:${{ inputs.version }}-${{matrix.file_tag.tag_suffix }}
            ${{ inputs.dockerhub_repo }}:latest-${{matrix.file_tag.tag_suffix }}
            ${{ inputs.ghcr_repo }}:${{ inputs.version }}-${{ matrix.file_tag.tag_suffix }}
            ${{ inputs.ghcr_repo }}:latest-${{ matrix.file_tag.tag_suffix }}
          cache-from: type=gha
          cache-to: type=gha
