# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: Force Build

on:
  workflow_dispatch:

jobs:
  force_build:
    uses: ./.github/workflows/component_build-images.yml
    with:
      push: true
      version: 'dev'
    secrets: inherit
